### PR TITLE
Modify podspec deployment target

### PR DESCRIPTION
**Pull request by jinuman**
I had needs to set the iOS deployment target to version 11 or higher. But it was 13 or higher, so I made PR to make deployment target down to `11 or higher` to make this universal.

In my opinion, supporting more versions will make this great project more accessible to more people.

## BE CAREFUL BEFORE MERGE

* I did run `swift test` and All passed. But I am not sure if there will be another side effect. 
* If you accept this PR, Please check before merge

### CODE REVIEW

**Comment by danielsaidi** [comment]
Thanks you! Looks great, it's just my mistake overlooking this file :) 

We could actually set iOS all the way down to 9, but 11 for iOS and tvOS works great.

Just one question before merging - why setting the Swift version to 5? I'm not sure if this has any other side-effects.

**Comment by jinuman** [comment]
Thank you. @danielsaidi. 

It looks like CocoaPods is just copying that value into the Xcode target's `SWIFT_VERSION`. I don't know the detail of and I'm not sure. But, my guess is that the `podspec` should specify the minimum Swift version required to compile the code. So if the code supports 5.0 ~ 5.3, the swift_version should be set to 5.0.

If my guess is wrong then I will happy to modify Swift version to 5.3 back :)

**Comment by danielsaidi** [comment]
Sounds great @jinuman - thank you! :)

**Comment by danielsaidi** [comment]
I have released this as a 0.9.1 👍

**Pull request merged**
